apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-loadbalancer
spec:
  selector:
    app: redis-cluster
  type: LoadBalancer
  ports:
  - name: http
    port: 6379
    targetPort: 8080
    protocol: TCP
